version: "3"
services:

  api:
    image: api
    container_name: api
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_HOST=db
    env_file:
      - .env
    build:
      context: ..
      dockerfile: ../Dockerfile
    entrypoint: ["./entrypoint.sh"]
    ports:
      - "8000:8000"

  db:
    image: postgres:14.1-alpine
    container_name: db
    env_file:
      - ../.env
    ports:
      - "5432:5432"
    tmpfs:
      - /var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
