"""Add Default Data to Currencies

Revision ID: 9ecdd5f10f6e
Revises: e5dcebb0833f
Create Date: 2024-02-28 00:37:42.147154

"""
from typing import Sequence, Union
from datetime import datetime

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '9ecdd5f10f6e'
down_revision: Union[str, None] = 'e5dcebb0833f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.bulk_insert(
        sa.Table(
            'currencies',
            sa.MetaData(),
            sa.Column('name', sa.String(length=10), nullable=False),
            sa.Column('last_update', sa.DateTime(timezone=True), nullable=False),
        ),
        [
            {
                'name': 'USD',
                'last_update': datetime.now()
            },
            {
                'name': 'EUR',
                'last_update': datetime.now()
            },
        ]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
