name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: pre-commit
      run: pre-commit run --all-files

    - name: Run tests
      run: pytest tests/

    - name: Measure code coverage
      run: |
        coverage run -m pytest tests/
        coverage report -m
